http local {
	endpoints { "/dns-query"; };
};

options {
	directory "/var/cache/bind";
	listen-on port 5353 { any; };
};

include "/etc/bind/my-rndc.key";
controls {
    inet 127.0.0.1 port 5354 allow { localhost; } keys { "rndc-key"; };
};

zone "localhost" IN {
    type primary;
    file "/etc/bind/db.localhost";
    allow-update { none; };
};
